config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/music', to: 'player#index', as: 'music'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
    @mp3_files = Dir.glob("public/mp3/*.mp3").map { |f| File.basename(f) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <h1>Welcome to our Music App!</h1>
  <p>Explore and enjoy your favorite tunes.</p>
  <%= link_to 'Explore Music', music_path, class: 'btn' %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>MP3 Player</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

<script type="module" src="/assets/player.js"></script>
</body>
</html>

app/views/player/index.html.erb
<!-- app/views/player/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>MP3 Player</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <%= link_to 'Home', root_path %>
</nav>

<div class="container">
  <h1>MP3 Player</h1>

  <div id="player-container">
    <ul id="playlist">
      <% @mp3_files.each do |file| %>
        <li><%= file %></li>
      <% end %>
    </ul>

    <div id="time-display"></div>
    
    <!-- Add Play/Pause buttons -->
    <button id="play-button">Play</button>
    <button id="pause-button">Pause</button>
  </div>
</div>

<script type="module" src="/assets/player.js"></script>
</body>
</html>